#!/bin/bash
WATER="$WATER" STIR="$STIR" python3 -c 'print(int(input(), len(os.environ["WATER"])) + int(input(), len(os.environ["STIR"])), end="")' | python3 -c 'print(int(input()), len(os.environ["WATER"]))'
