#!/usr/bin/env bash
# This script displays a list of currently running processes for all users, including those without a TTY, in a user-oriented format, showing the process hierarchy.

# Using the ps command with the appropriate flags to show all processes, in a hierarchical format
ps -e -o pid,ppid,uid,user,cmd --forest
