#!/usr/bin/env bash
# This script displays a list of currently running processes for all users, including those which might not have a TTY, in a user-oriented format and shows the process hierarchy.

ps -e --forest -o user,pid,ppid,tty,stat,time,cmd
